"""
Configuration constants for BlazeFace detection.
"""

# Anchor configuration
SMALL_GRID_SIZE = 16
BIG_GRID_SIZE = 8
SMALL_ANCHORS_PER_CELL = 2
BIG_ANCHORS_PER_CELL = 6
TOTAL_ANCHORS = 896  # 16*16*2 + 8*8*6

# Default paths
DEFAULT_WEIGHTS_PATH = "model_weights/blazeface.pth"
DEFAULT_DATA_ROOT = "data/raw/blazeface"
DEFAULT_TRAIN_CSV = "data/splits/train.csv"
DEFAULT_VAL_CSV = "data/splits/val.csv"
DEFAULT_CHECKPOINT_DIR = "runs/checkpoints"
DEFAULT_BEST_CHECKPOINT = "runs/checkpoints/BlazeFace_best.pth"
DEFAULT_LOG_DIR = "runs/logs"

# Training hyperparameters
DEFAULT_BATCH_SIZE = 32
DEFAULT_EPOCHS = 20
DEFAULT_LEARNING_RATE = 1e-4
DEFAULT_WEIGHT_DECAY = 1e-4
DEFAULT_NUM_WORKERS = 4
DEFAULT_SAVE_EVERY = 10

# Model parameters
DEFAULT_INPUT_SIZE = 128
DEFAULT_DETECTION_THRESHOLD = 0.9
DEFAULT_TRAIN_THRESHOLD = 0.2
DEFAULT_NMS_IOU_THRESHOLD = 0.2

# Debug/inference defaults
DEFAULT_DEBUG_WEIGHTS = DEFAULT_BEST_CHECKPOINT
DEFAULT_SECONDARY_WEIGHTS = DEFAULT_WEIGHTS_PATH
DEFAULT_COMPARE_THRESHOLD = 0.2
DEFAULT_COMPARE_LABEL = "Mediapipe"
DEFAULT_DETECTOR_THRESHOLD_DEBUG = 0.5
DEFAULT_SCREENSHOT_OUTPUT = "runs/logs/debug_images"
DEFAULT_SCREENSHOT_COUNT = 10
DEFAULT_SCREENSHOT_MIN_FACES = 2
DEFAULT_SCREENSHOT_CANDIDATES = 20
DEFAULT_EVAL_MAX_IMAGES = 500
DEFAULT_EVAL_SCORE_THRESHOLD = 0.5
DEFAULT_EVAL_IOU_THRESHOLD = 0.5
